---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: in-cluster
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: in-cluster-with-cluster-admin
subjects:
  - kind: ServiceAccount
    name: in-cluster
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: in-cluster
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: in-cluster
  template:
    metadata:
      labels:
        app: in-cluster
    spec:
      serviceAccount: in-cluster
      containers:
        - name: centos
          image: in-cluster:latest
          imagePullPolicy: IfNotPresent
          command: ["/app/in-cluster"]
